---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    component: velero
  name: node-agent
  namespace: velero
spec:
  selector:
    matchLabels:
      name: node-agent
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: velero
        name: node-agent
    spec:
      containers:
        - args:
            - node-agent
            - server
          command:
            - /velero
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VELERO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: VELERO_SCRATCH_DIR
              value: /scratch
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /credentials/cloud
            - name: AZURE_CREDENTIALS_FILE
              value: /credentials/cloud
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /credentials/cloud
          image: velero/velero:latest
          imagePullPolicy: Always
          name: node-agent
          resources: {}
          volumeMounts:
            - mountPath: /host_pods
              mountPropagation: HostToContainer
              name: host-pods
            - mountPath: /scratch
              name: scratch
            - mountPath: /credentials
              name: cloud-credentials
      securityContext:
        runAsUser: 0
      serviceAccountName: velero
      volumes:
        - hostPath:
            path: /var/lib/kubelet/pods
          name: host-pods
        - emptyDir: {}
          name: scratch
        - name: cloud-credentials
          secret:
            secretName: cloud-credentials
  updateStrategy: {}
