addReviewers: true
addAssignees: author

# Only require 2, random reviewers.
# TODO expand this to support using reviewGroups
numberOfReviewers: 2

reviewers:
  - nrb
  - ashish-amarnath
  - carlisia
  - zubron
  - dsu-igeek
  - jenting
  - sseago
