# Copyright 2017 Heptio Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ARG_FROM
MAINTAINER Andy Goldstein "andy@heptio.com"

RUN apk add --no-cache ca-certificates && \
    adduser -S -D -H -u 1000 ark

ADD _output/ARG_ARCH/ARG_BIN /ARG_BIN

USER ark
ENTRYPOINT ["/ark"]
