# Copyright 2017, 2019 the Velero contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM debian:stretch-slim

LABEL maintainer="Steve Kriss <krisss@vmware.com>"

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates wget bzip2 && \
    wget --quiet https://github.com/restic/restic/releases/download/v0.9.4/restic_0.9.4_linux_amd64.bz2 && \
    bunzip2 restic_0.9.4_linux_amd64.bz2 && \
    mv restic_0.9.4_linux_amd64 /usr/bin/restic && \
    chmod +x /usr/bin/restic && \
    apt-get remove -y wget bzip2 && \
    rm -rf /var/lib/apt/lists/*


ADD /bin/linux/amd64/velero /velero

USER nobody:nobody

ENTRYPOINT ["/velero"]
