# Copyright 2019 the Velero contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ubuntu:bionic

LABEL maintainer="Steve Kriss <krisss@vmware.com>"

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates wget && \
    wget --quiet https://oplab9.parqtec.unicamp.br/pub/ppc64el/restic/restic-0.9.5 && \
    mv restic-0.9.5 /usr/bin/restic && \
    chmod +x /usr/bin/restic && \
    apt-get remove -y wget && \
    rm -rf /var/lib/apt/lists/*


ADD /bin/linux/ppc64le/velero /velero

USER nobody:nobody

ENTRYPOINT ["/velero"]
