// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/vmware-tanzu/velero/pkg/uploader/cbt/types"
)

// NewBitmap creates a new instance of Bitmap. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBitmap(t interface {
	mock.TestingT
	Cleanup(func())
}) *Bitmap {
	mock := &Bitmap{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Bitmap is an autogenerated mock type for the Bitmap type
type Bitmap struct {
	mock.Mock
}

type Bitmap_Expecter struct {
	mock *mock.Mock
}

func (_m *Bitmap) EXPECT() *Bitmap_Expecter {
	return &Bitmap_Expecter{mock: &_m.Mock}
}

// ChangeID provides a mock function for the type Bitmap
func (_mock *Bitmap) ChangeID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChangeID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Bitmap_ChangeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeID'
type Bitmap_ChangeID_Call struct {
	*mock.Call
}

// ChangeID is a helper method to define mock.On call
func (_e *Bitmap_Expecter) ChangeID() *Bitmap_ChangeID_Call {
	return &Bitmap_ChangeID_Call{Call: _e.mock.On("ChangeID")}
}

func (_c *Bitmap_ChangeID_Call) Run(run func()) *Bitmap_ChangeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Bitmap_ChangeID_Call) Return(s string) *Bitmap_ChangeID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Bitmap_ChangeID_Call) RunAndReturn(run func() string) *Bitmap_ChangeID_Call {
	_c.Call.Return(run)
	return _c
}

// Iterator provides a mock function for the type Bitmap
func (_mock *Bitmap) Iterator() types.Iterator {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Iterator")
	}

	var r0 types.Iterator
	if returnFunc, ok := ret.Get(0).(func() types.Iterator); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Iterator)
		}
	}
	return r0
}

// Bitmap_Iterator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Iterator'
type Bitmap_Iterator_Call struct {
	*mock.Call
}

// Iterator is a helper method to define mock.On call
func (_e *Bitmap_Expecter) Iterator() *Bitmap_Iterator_Call {
	return &Bitmap_Iterator_Call{Call: _e.mock.On("Iterator")}
}

func (_c *Bitmap_Iterator_Call) Run(run func()) *Bitmap_Iterator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Bitmap_Iterator_Call) Return(iterator types.Iterator) *Bitmap_Iterator_Call {
	_c.Call.Return(iterator)
	return _c
}

func (_c *Bitmap_Iterator_Call) RunAndReturn(run func() types.Iterator) *Bitmap_Iterator_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type Bitmap
func (_mock *Bitmap) Set(v uint64, v1 uint64) {
	_mock.Called(v, v1)
	return
}

// Bitmap_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type Bitmap_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - v uint64
//   - v1 uint64
func (_e *Bitmap_Expecter) Set(v interface{}, v1 interface{}) *Bitmap_Set_Call {
	return &Bitmap_Set_Call{Call: _e.mock.On("Set", v, v1)}
}

func (_c *Bitmap_Set_Call) Run(run func(v uint64, v1 uint64)) *Bitmap_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Bitmap_Set_Call) Return() *Bitmap_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *Bitmap_Set_Call) RunAndReturn(run func(v uint64, v1 uint64)) *Bitmap_Set_Call {
	_c.Run(run)
	return _c
}

// SetFull provides a mock function for the type Bitmap
func (_mock *Bitmap) SetFull() {
	_mock.Called()
	return
}

// Bitmap_SetFull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFull'
type Bitmap_SetFull_Call struct {
	*mock.Call
}

// SetFull is a helper method to define mock.On call
func (_e *Bitmap_Expecter) SetFull() *Bitmap_SetFull_Call {
	return &Bitmap_SetFull_Call{Call: _e.mock.On("SetFull")}
}

func (_c *Bitmap_SetFull_Call) Run(run func()) *Bitmap_SetFull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Bitmap_SetFull_Call) Return() *Bitmap_SetFull_Call {
	_c.Call.Return()
	return _c
}

func (_c *Bitmap_SetFull_Call) RunAndReturn(run func()) *Bitmap_SetFull_Call {
	_c.Run(run)
	return _c
}

// Snapshot provides a mock function for the type Bitmap
func (_mock *Bitmap) Snapshot() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Snapshot")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Bitmap_Snapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshot'
type Bitmap_Snapshot_Call struct {
	*mock.Call
}

// Snapshot is a helper method to define mock.On call
func (_e *Bitmap_Expecter) Snapshot() *Bitmap_Snapshot_Call {
	return &Bitmap_Snapshot_Call{Call: _e.mock.On("Snapshot")}
}

func (_c *Bitmap_Snapshot_Call) Run(run func()) *Bitmap_Snapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Bitmap_Snapshot_Call) Return(s string) *Bitmap_Snapshot_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Bitmap_Snapshot_Call) RunAndReturn(run func() string) *Bitmap_Snapshot_Call {
	_c.Call.Return(run)
	return _c
}

// VolumeID provides a mock function for the type Bitmap
func (_mock *Bitmap) VolumeID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for VolumeID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Bitmap_VolumeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VolumeID'
type Bitmap_VolumeID_Call struct {
	*mock.Call
}

// VolumeID is a helper method to define mock.On call
func (_e *Bitmap_Expecter) VolumeID() *Bitmap_VolumeID_Call {
	return &Bitmap_VolumeID_Call{Call: _e.mock.On("VolumeID")}
}

func (_c *Bitmap_VolumeID_Call) Run(run func()) *Bitmap_VolumeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Bitmap_VolumeID_Call) Return(s string) *Bitmap_VolumeID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Bitmap_VolumeID_Call) RunAndReturn(run func() string) *Bitmap_VolumeID_Call {
	_c.Call.Return(run)
	return _c
}
