// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewIterator creates a new instance of Iterator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIterator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Iterator {
	mock := &Iterator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Iterator is an autogenerated mock type for the Iterator type
type Iterator struct {
	mock.Mock
}

type Iterator_Expecter struct {
	mock *mock.Mock
}

func (_m *Iterator) EXPECT() *Iterator_Expecter {
	return &Iterator_Expecter{mock: &_m.Mock}
}

// BlockSize provides a mock function for the type Iterator
func (_mock *Iterator) BlockSize() uint {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BlockSize")
	}

	var r0 uint
	if returnFunc, ok := ret.Get(0).(func() uint); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint)
	}
	return r0
}

// Iterator_BlockSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockSize'
type Iterator_BlockSize_Call struct {
	*mock.Call
}

// BlockSize is a helper method to define mock.On call
func (_e *Iterator_Expecter) BlockSize() *Iterator_BlockSize_Call {
	return &Iterator_BlockSize_Call{Call: _e.mock.On("BlockSize")}
}

func (_c *Iterator_BlockSize_Call) Run(run func()) *Iterator_BlockSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Iterator_BlockSize_Call) Return(v uint) *Iterator_BlockSize_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *Iterator_BlockSize_Call) RunAndReturn(run func() uint) *Iterator_BlockSize_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeID provides a mock function for the type Iterator
func (_mock *Iterator) ChangeID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChangeID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Iterator_ChangeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeID'
type Iterator_ChangeID_Call struct {
	*mock.Call
}

// ChangeID is a helper method to define mock.On call
func (_e *Iterator_Expecter) ChangeID() *Iterator_ChangeID_Call {
	return &Iterator_ChangeID_Call{Call: _e.mock.On("ChangeID")}
}

func (_c *Iterator_ChangeID_Call) Run(run func()) *Iterator_ChangeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Iterator_ChangeID_Call) Return(s string) *Iterator_ChangeID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Iterator_ChangeID_Call) RunAndReturn(run func() string) *Iterator_ChangeID_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type Iterator
func (_mock *Iterator) Count() uint64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 uint64
	if returnFunc, ok := ret.Get(0).(func() uint64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint64)
	}
	return r0
}

// Iterator_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type Iterator_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
func (_e *Iterator_Expecter) Count() *Iterator_Count_Call {
	return &Iterator_Count_Call{Call: _e.mock.On("Count")}
}

func (_c *Iterator_Count_Call) Run(run func()) *Iterator_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Iterator_Count_Call) Return(v uint64) *Iterator_Count_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *Iterator_Count_Call) RunAndReturn(run func() uint64) *Iterator_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function for the type Iterator
func (_mock *Iterator) Next() (uint64, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 uint64
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (uint64, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() uint64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// Iterator_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type Iterator_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *Iterator_Expecter) Next() *Iterator_Next_Call {
	return &Iterator_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *Iterator_Next_Call) Run(run func()) *Iterator_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Iterator_Next_Call) Return(v uint64, b bool) *Iterator_Next_Call {
	_c.Call.Return(v, b)
	return _c
}

func (_c *Iterator_Next_Call) RunAndReturn(run func() (uint64, bool)) *Iterator_Next_Call {
	_c.Call.Return(run)
	return _c
}

// Snapshot provides a mock function for the type Iterator
func (_mock *Iterator) Snapshot() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Snapshot")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Iterator_Snapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshot'
type Iterator_Snapshot_Call struct {
	*mock.Call
}

// Snapshot is a helper method to define mock.On call
func (_e *Iterator_Expecter) Snapshot() *Iterator_Snapshot_Call {
	return &Iterator_Snapshot_Call{Call: _e.mock.On("Snapshot")}
}

func (_c *Iterator_Snapshot_Call) Run(run func()) *Iterator_Snapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Iterator_Snapshot_Call) Return(s string) *Iterator_Snapshot_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Iterator_Snapshot_Call) RunAndReturn(run func() string) *Iterator_Snapshot_Call {
	_c.Call.Return(run)
	return _c
}

// VolumeID provides a mock function for the type Iterator
func (_mock *Iterator) VolumeID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for VolumeID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Iterator_VolumeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VolumeID'
type Iterator_VolumeID_Call struct {
	*mock.Call
}

// VolumeID is a helper method to define mock.On call
func (_e *Iterator_Expecter) VolumeID() *Iterator_VolumeID_Call {
	return &Iterator_VolumeID_Call{Call: _e.mock.On("VolumeID")}
}

func (_c *Iterator_VolumeID_Call) Run(run func()) *Iterator_VolumeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Iterator_VolumeID_Call) Return(s string) *Iterator_VolumeID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Iterator_VolumeID_Call) RunAndReturn(run func() string) *Iterator_VolumeID_Call {
	_c.Call.Return(run)
	return _c
}
