// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	v1 "github.com/vmware-tanzu/velero/pkg/apis/velero/v1"
)

// PostRestoreAction is an autogenerated mock type for the PostRestoreAction type
type PostRestoreAction struct {
	mock.Mock
}

// Execute provides a mock function with given fields: restore
func (_m *PostRestoreAction) Execute(restore *v1.Restore) error {
	ret := _m.Called(restore)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.Restore) error); ok {
		r0 = rf(restore)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewPostRestoreAction interface {
	mock.TestingT
	Cleanup(func())
}

// NewPostRestoreAction creates a new instance of PostRestoreAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPostRestoreAction(t mockConstructorTestingTNewPostRestoreAction) *PostRestoreAction {
	mock := &PostRestoreAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
