// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	v1 "github.com/vmware-tanzu/velero/pkg/apis/velero/v1"
)

// PostBackupAction is an autogenerated mock type for the PostBackupAction type
type PostBackupAction struct {
	mock.Mock
}

// Execute provides a mock function with given fields: backup
func (_m *PostBackupAction) Execute(backup *v1.Backup) error {
	ret := _m.Called(backup)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.Backup) error); ok {
		r0 = rf(backup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewPostBackupAction interface {
	mock.TestingT
	Cleanup(func())
}

// NewPostBackupAction creates a new instance of PostBackupAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPostBackupAction(t mockConstructorTestingTNewPostBackupAction) *PostBackupAction {
	mock := &PostBackupAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
