// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	v1 "github.com/vmware-tanzu/velero/pkg/apis/velero/v1"
)

// PreBackupAction is an autogenerated mock type for the PreBackupAction type
type PreBackupAction struct {
	mock.Mock
}

// Execute provides a mock function with given fields: backup
func (_m *PreBackupAction) Execute(backup *v1.Backup) error {
	ret := _m.Called(backup)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.Backup) error); ok {
		r0 = rf(backup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewPreBackupAction interface {
	mock.TestingT
	Cleanup(func())
}

// NewPreBackupAction creates a new instance of PreBackupAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPreBackupAction(t mockConstructorTestingTNewPreBackupAction) *PreBackupAction {
	mock := &PreBackupAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
