apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels: 
    component: velero

secretGenerator:
- name: cloud-credentials
  namespace: velero
  files:
  - "cloud"