// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	udmrepo "github.com/vmware-tanzu/velero/pkg/repository/udmrepo"
)

// ObjectWriter is an autogenerated mock type for the ObjectWriter type
type ObjectWriter struct {
	mock.Mock
}

// Checkpoint provides a mock function with given fields:
func (_m *ObjectWriter) Checkpoint() (udmrepo.ID, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Checkpoint")
	}

	var r0 udmrepo.ID
	var r1 error
	if rf, ok := ret.Get(0).(func() (udmrepo.ID, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() udmrepo.ID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(udmrepo.ID)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Close provides a mock function with given fields:
func (_m *ObjectWriter) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Result provides a mock function with given fields:
func (_m *ObjectWriter) Result() (udmrepo.ID, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Result")
	}

	var r0 udmrepo.ID
	var r1 error
	if rf, ok := ret.Get(0).(func() (udmrepo.ID, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() udmrepo.ID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(udmrepo.ID)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Seek provides a mock function with given fields: offset, whence
func (_m *ObjectWriter) Seek(offset int64, whence int) (int64, error) {
	ret := _m.Called(offset, whence)

	if len(ret) == 0 {
		panic("no return value specified for Seek")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int) (int64, error)); ok {
		return rf(offset, whence)
	}
	if rf, ok := ret.Get(0).(func(int64, int) int64); ok {
		r0 = rf(offset, whence)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(int64, int) error); ok {
		r1 = rf(offset, whence)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Write provides a mock function with given fields: p
func (_m *ObjectWriter) Write(p []byte) (int, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewObjectWriter creates a new instance of ObjectWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewObjectWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ObjectWriter {
	mock := &ObjectWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
