// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"
import v1 "github.com/heptio/ark/pkg/apis/ark/v1"

// XXXBackupGetter is an autogenerated mock type for the XXXBackupGetter type
type XXXBackupGetter struct {
	mock.Mock
}

// GetBackup provides a mock function with given fields: bucket, backupName
func (_m *XXXBackupGetter) GetBackup(bucket string, backupName string) (*v1.Backup, error) {
	ret := _m.Called(bucket, backupName)

	var r0 *v1.Backup
	if rf, ok := ret.Get(0).(func(string, string) *v1.Backup); ok {
		r0 = rf(bucket, backupName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Backup)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(bucket, backupName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
