// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	blob "github.com/kopia/kopia/repo/blob"
	content "github.com/kopia/kopia/repo/content"

	context "context"

	index "github.com/kopia/kopia/repo/content/index"

	manifest "github.com/kopia/kopia/repo/manifest"

	mock "github.com/stretchr/testify/mock"

	object "github.com/kopia/kopia/repo/object"

	repo "github.com/kopia/kopia/repo"

	throttling "github.com/kopia/kopia/repo/blob/throttling"

	time "time"
)

// DirectRepositoryWriter is an autogenerated mock type for the DirectRepositoryWriter type
type DirectRepositoryWriter struct {
	mock.Mock
}

// AlsoLogToContentLog provides a mock function with given fields: ctx
func (_m *DirectRepositoryWriter) AlsoLogToContentLog(ctx context.Context) context.Context {
	ret := _m.Called(ctx)

	var r0 context.Context
	if rf, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// BlobCfg provides a mock function with given fields:
func (_m *DirectRepositoryWriter) BlobCfg() content.BlobCfgBlob {
	ret := _m.Called()

	var r0 content.BlobCfgBlob
	if rf, ok := ret.Get(0).(func() content.BlobCfgBlob); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(content.BlobCfgBlob)
	}

	return r0
}

// BlobReader provides a mock function with given fields:
func (_m *DirectRepositoryWriter) BlobReader() blob.Reader {
	ret := _m.Called()

	var r0 blob.Reader
	if rf, ok := ret.Get(0).(func() blob.Reader); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(blob.Reader)
		}
	}

	return r0
}

// BlobStorage provides a mock function with given fields:
func (_m *DirectRepositoryWriter) BlobStorage() blob.Storage {
	ret := _m.Called()

	var r0 blob.Storage
	if rf, ok := ret.Get(0).(func() blob.Storage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(blob.Storage)
		}
	}

	return r0
}

// BlobVolume provides a mock function with given fields:
func (_m *DirectRepositoryWriter) BlobVolume() blob.Volume {
	ret := _m.Called()

	var r0 blob.Volume
	if rf, ok := ret.Get(0).(func() blob.Volume); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(blob.Volume)
		}
	}

	return r0
}

// ChangePassword provides a mock function with given fields: ctx, newPassword
func (_m *DirectRepositoryWriter) ChangePassword(ctx context.Context, newPassword string) error {
	ret := _m.Called(ctx, newPassword)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClientOptions provides a mock function with given fields:
func (_m *DirectRepositoryWriter) ClientOptions() repo.ClientOptions {
	ret := _m.Called()

	var r0 repo.ClientOptions
	if rf, ok := ret.Get(0).(func() repo.ClientOptions); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(repo.ClientOptions)
	}

	return r0
}

// Close provides a mock function with given fields: ctx
func (_m *DirectRepositoryWriter) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CommitUpgrade provides a mock function with given fields: ctx
func (_m *DirectRepositoryWriter) CommitUpgrade(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConfigFilename provides a mock function with given fields:
func (_m *DirectRepositoryWriter) ConfigFilename() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ContentInfo provides a mock function with given fields: ctx, contentID
func (_m *DirectRepositoryWriter) ContentInfo(ctx context.Context, contentID index.ID) (index.Info, error) {
	ret := _m.Called(ctx, contentID)

	var r0 index.Info
	if rf, ok := ret.Get(0).(func(context.Context, index.ID) index.Info); ok {
		r0 = rf(ctx, contentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(index.Info)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, index.ID) error); ok {
		r1 = rf(ctx, contentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContentManager provides a mock function with given fields:
func (_m *DirectRepositoryWriter) ContentManager() *content.WriteManager {
	ret := _m.Called()

	var r0 *content.WriteManager
	if rf, ok := ret.Get(0).(func() *content.WriteManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*content.WriteManager)
		}
	}

	return r0
}

// ContentReader provides a mock function with given fields:
func (_m *DirectRepositoryWriter) ContentReader() content.Reader {
	ret := _m.Called()

	var r0 content.Reader
	if rf, ok := ret.Get(0).(func() content.Reader); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(content.Reader)
		}
	}

	return r0
}

// Crypter provides a mock function with given fields:
func (_m *DirectRepositoryWriter) Crypter() *content.Crypter {
	ret := _m.Called()

	var r0 *content.Crypter
	if rf, ok := ret.Get(0).(func() *content.Crypter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*content.Crypter)
		}
	}

	return r0
}

// DeleteManifest provides a mock function with given fields: ctx, id
func (_m *DirectRepositoryWriter) DeleteManifest(ctx context.Context, id manifest.ID) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, manifest.ID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeriveKey provides a mock function with given fields: purpose, keyLength
func (_m *DirectRepositoryWriter) DeriveKey(purpose []byte, keyLength int) []byte {
	ret := _m.Called(purpose, keyLength)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte, int) []byte); ok {
		r0 = rf(purpose, keyLength)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// DisableIndexRefresh provides a mock function with given fields:
func (_m *DirectRepositoryWriter) DisableIndexRefresh() {
	_m.Called()
}

// FindManifests provides a mock function with given fields: ctx, labels
func (_m *DirectRepositoryWriter) FindManifests(ctx context.Context, labels map[string]string) ([]*manifest.EntryMetadata, error) {
	ret := _m.Called(ctx, labels)

	var r0 []*manifest.EntryMetadata
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) []*manifest.EntryMetadata); ok {
		r0 = rf(ctx, labels)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*manifest.EntryMetadata)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, map[string]string) error); ok {
		r1 = rf(ctx, labels)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Flush provides a mock function with given fields: ctx
func (_m *DirectRepositoryWriter) Flush(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetManifest provides a mock function with given fields: ctx, id, data
func (_m *DirectRepositoryWriter) GetManifest(ctx context.Context, id manifest.ID, data interface{}) (*manifest.EntryMetadata, error) {
	ret := _m.Called(ctx, id, data)

	var r0 *manifest.EntryMetadata
	if rf, ok := ret.Get(0).(func(context.Context, manifest.ID, interface{}) *manifest.EntryMetadata); ok {
		r0 = rf(ctx, id, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*manifest.EntryMetadata)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, manifest.ID, interface{}) error); ok {
		r1 = rf(ctx, id, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IndexBlobs provides a mock function with given fields: ctx, includeInactive
func (_m *DirectRepositoryWriter) IndexBlobs(ctx context.Context, includeInactive bool) ([]content.IndexBlobInfo, error) {
	ret := _m.Called(ctx, includeInactive)

	var r0 []content.IndexBlobInfo
	if rf, ok := ret.Get(0).(func(context.Context, bool) []content.IndexBlobInfo); ok {
		r0 = rf(ctx, includeInactive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]content.IndexBlobInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = rf(ctx, includeInactive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDirectWriter provides a mock function with given fields: ctx, opt
func (_m *DirectRepositoryWriter) NewDirectWriter(ctx context.Context, opt repo.WriteSessionOptions) (context.Context, repo.DirectRepositoryWriter, error) {
	ret := _m.Called(ctx, opt)

	var r0 context.Context
	if rf, ok := ret.Get(0).(func(context.Context, repo.WriteSessionOptions) context.Context); ok {
		r0 = rf(ctx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	var r1 repo.DirectRepositoryWriter
	if rf, ok := ret.Get(1).(func(context.Context, repo.WriteSessionOptions) repo.DirectRepositoryWriter); ok {
		r1 = rf(ctx, opt)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(repo.DirectRepositoryWriter)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, repo.WriteSessionOptions) error); ok {
		r2 = rf(ctx, opt)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewObjectWriter provides a mock function with given fields: ctx, opt
func (_m *DirectRepositoryWriter) NewObjectWriter(ctx context.Context, opt object.WriterOptions) object.Writer {
	ret := _m.Called(ctx, opt)

	var r0 object.Writer
	if rf, ok := ret.Get(0).(func(context.Context, object.WriterOptions) object.Writer); ok {
		r0 = rf(ctx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(object.Writer)
		}
	}

	return r0
}

// NewWriter provides a mock function with given fields: ctx, opt
func (_m *DirectRepositoryWriter) NewWriter(ctx context.Context, opt repo.WriteSessionOptions) (context.Context, repo.RepositoryWriter, error) {
	ret := _m.Called(ctx, opt)

	var r0 context.Context
	if rf, ok := ret.Get(0).(func(context.Context, repo.WriteSessionOptions) context.Context); ok {
		r0 = rf(ctx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	var r1 repo.RepositoryWriter
	if rf, ok := ret.Get(1).(func(context.Context, repo.WriteSessionOptions) repo.RepositoryWriter); ok {
		r1 = rf(ctx, opt)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(repo.RepositoryWriter)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, repo.WriteSessionOptions) error); ok {
		r2 = rf(ctx, opt)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ObjectFormat provides a mock function with given fields:
func (_m *DirectRepositoryWriter) ObjectFormat() object.Format {
	ret := _m.Called()

	var r0 object.Format
	if rf, ok := ret.Get(0).(func() object.Format); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(object.Format)
	}

	return r0
}

// OpenObject provides a mock function with given fields: ctx, id
func (_m *DirectRepositoryWriter) OpenObject(ctx context.Context, id object.ID) (object.Reader, error) {
	ret := _m.Called(ctx, id)

	var r0 object.Reader
	if rf, ok := ret.Get(0).(func(context.Context, object.ID) object.Reader); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(object.Reader)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, object.ID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PrefetchContents provides a mock function with given fields: ctx, contentIDs, hint
func (_m *DirectRepositoryWriter) PrefetchContents(ctx context.Context, contentIDs []index.ID, hint string) []index.ID {
	ret := _m.Called(ctx, contentIDs, hint)

	var r0 []index.ID
	if rf, ok := ret.Get(0).(func(context.Context, []index.ID, string) []index.ID); ok {
		r0 = rf(ctx, contentIDs, hint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]index.ID)
		}
	}

	return r0
}

// PrefetchObjects provides a mock function with given fields: ctx, objectIDs, hint
func (_m *DirectRepositoryWriter) PrefetchObjects(ctx context.Context, objectIDs []object.ID, hint string) ([]index.ID, error) {
	ret := _m.Called(ctx, objectIDs, hint)

	var r0 []index.ID
	if rf, ok := ret.Get(0).(func(context.Context, []object.ID, string) []index.ID); ok {
		r0 = rf(ctx, objectIDs, hint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]index.ID)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []object.ID, string) error); ok {
		r1 = rf(ctx, objectIDs, hint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutManifest provides a mock function with given fields: ctx, labels, payload
func (_m *DirectRepositoryWriter) PutManifest(ctx context.Context, labels map[string]string, payload interface{}) (manifest.ID, error) {
	ret := _m.Called(ctx, labels, payload)

	var r0 manifest.ID
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string, interface{}) manifest.ID); ok {
		r0 = rf(ctx, labels, payload)
	} else {
		r0 = ret.Get(0).(manifest.ID)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, map[string]string, interface{}) error); ok {
		r1 = rf(ctx, labels, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Refresh provides a mock function with given fields: ctx
func (_m *DirectRepositoryWriter) Refresh(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RollbackUpgrade provides a mock function with given fields: ctx
func (_m *DirectRepositoryWriter) RollbackUpgrade(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetParameters provides a mock function with given fields: ctx, m, blobcfg
func (_m *DirectRepositoryWriter) SetParameters(ctx context.Context, m content.MutableParameters, blobcfg content.BlobCfgBlob) error {
	ret := _m.Called(ctx, m, blobcfg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, content.MutableParameters, content.BlobCfgBlob) error); ok {
		r0 = rf(ctx, m, blobcfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetUpgradeLockIntent provides a mock function with given fields: ctx, l
func (_m *DirectRepositoryWriter) SetUpgradeLockIntent(ctx context.Context, l content.UpgradeLock) (*content.UpgradeLock, error) {
	ret := _m.Called(ctx, l)

	var r0 *content.UpgradeLock
	if rf, ok := ret.Get(0).(func(context.Context, content.UpgradeLock) *content.UpgradeLock); ok {
		r0 = rf(ctx, l)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*content.UpgradeLock)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, content.UpgradeLock) error); ok {
		r1 = rf(ctx, l)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Throttler provides a mock function with given fields:
func (_m *DirectRepositoryWriter) Throttler() throttling.SettableThrottler {
	ret := _m.Called()

	var r0 throttling.SettableThrottler
	if rf, ok := ret.Get(0).(func() throttling.SettableThrottler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(throttling.SettableThrottler)
		}
	}

	return r0
}

// Time provides a mock function with given fields:
func (_m *DirectRepositoryWriter) Time() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// Token provides a mock function with given fields: password
func (_m *DirectRepositoryWriter) Token(password string) (string, error) {
	ret := _m.Called(password)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UniqueID provides a mock function with given fields:
func (_m *DirectRepositoryWriter) UniqueID() []byte {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// UpdateDescription provides a mock function with given fields: d
func (_m *DirectRepositoryWriter) UpdateDescription(d string) {
	_m.Called(d)
}

// VerifyObject provides a mock function with given fields: ctx, id
func (_m *DirectRepositoryWriter) VerifyObject(ctx context.Context, id object.ID) ([]index.ID, error) {
	ret := _m.Called(ctx, id)

	var r0 []index.ID
	if rf, ok := ret.Get(0).(func(context.Context, object.ID) []index.ID); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]index.ID)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, object.ID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewDirectRepositoryWriter interface {
	mock.TestingT
	Cleanup(func())
}

// NewDirectRepositoryWriter creates a new instance of DirectRepositoryWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDirectRepositoryWriter(t mockConstructorTestingTNewDirectRepositoryWriter) *DirectRepositoryWriter {
	mock := &DirectRepositoryWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
