name: Pull Request Linter Check
on:
  pull_request:
    # Do not run when the change only includes these directories.
    paths-ignore:
      - "site/**"
      - "design/**"
      - "**/*.md"
jobs:
  build:
    name: Run Linter Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v5

      - name: Extract Go version from go.mod if target branch is main
        id: main-go-version
        if: github.event.pull_request.base.ref == 'main'
        run: |
          # Extract the version (e.g. 1.24.0, or 1.24)
          originVersion=$(grep '^go ' go.mod | awk '{print $2}')

          # Only keep the major and minor version (1.24)
          version=$(echo "$originVersion" | cut -d. -f1-2)

          echo "version=$version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Set up Go for main branch
        if: github.event.pull_request.base.ref == 'main'
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.main-go-version.outputs.version }}

      - name: Set up Go for released branches
        if: github.event.pull_request.base.ref != 'main'
        uses: actions/setup-go@v5
        with: 
            go-version-file: go.mod

      # Display the setup Go version
      - run: go version

      - name: Linter check
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.1
          args: --verbose
